steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
    - 'DOCKER_BUILDKIT=1'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}'
    - '-f'
    - 'Dockerfile'
    - '--annotation'
    - 'com.google.cloudmarketplace.product.service.name=rapd'
    - '.'
images:
- 'gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}'
