steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - '--destination=gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}'
    - '--dockerfile=Dockerfile'
    - '--context=.'
    - '--annotation=com.googleapis.cloudmarketplace.product.service.name=rapd'
images:
- 'gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}'
