steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
    - 'DOCKER_BUILDKIT=1'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}'
    - '-f'
    - 'Dockerfile'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      set -e
      apt-get update && apt-get install -y wget
      wget -qO- https://github.com/google/go-containerregistry/releases/download/v0.20.6/go-containerregistry_Linux_x86_64.tar.gz \
        | tar -zxf - crane && install -m 755 crane /usr/local/bin/crane

      # Annotate the built image
      crane mutate gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG} \
        --annotation com.googleapis.cloudmarketplace.product.service.name=services/rapd \
        --tag gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}
      crane mutate gcr.io/pentiumnetwork-rapd-public/rapd:1.0.0 \
        --annotation com.googleapis.cloudmarketplace.product.service.name=services/rapd \
        --tag gcr.io/pentiumnetwork-rapd-public/rapd:1.0.0

images:
- 'gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}'
