steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}', '-f', 'Dockerfile', '.']
images:
- 'gcr.io/pentiumnetwork-rapd-public/rapd/deployer:${_TAG}'

