
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-postgresql" .Release.Name)) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql-server
type: Opaque
data:
{{- if $secret }}
  postgres-password: {{ index $secret.data "postgres-password" }}
  password: {{ index $secret.data "password" }}
{{- else }}
  postgres-password: {{ randAlphaNum 32 | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc |quote }}
{{- end }}
---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-postgres-from-schema-claim" .Release.Name)) -}}
apiVersion: v1
{{- if $secret }}
data:
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace  (printf "%s-postgres-from-schema-claim" .Release.Name)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- if  $secretData }}
    {{- range $oldkey, $oldvalue := $secretData }}
    {{ $oldkey }}: {{ $oldvalue | quote }}
    {{- end }}
  {{- end }}
{{- else }}
stringData:
  postgres-from-schema-claim: |
    INSTANCE_NAME=postgres-instance-1
    DATABASE_NAME=postgres
    SCHEMA_NAME=rapd
    HOST={{ .Release.Name }}-postgresql-svc.{{ .Release.Namespace }}
    PORT=5432
    USERNAME=rapd
    PASSWORD={{ randAlphaNum 32 }}
{{- end }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-from-schema-claim
type: Opaque
---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-postgres-pare-eventing-from-claim" .Release.Name)) -}}
apiVersion: v1
{{- if $secret }}
data:
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace  (printf "%s-postgres-pare-eventing-from-claim" .Release.Name)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- if  $secretData }}
    {{- range $oldkey, $oldvalue := $secretData }}
    {{ $oldkey }}: {{ $oldvalue | quote }}
    {{- end }}
  {{- end }}
{{- else }}
stringData:
  postgres-pare-eventing-from-claim: |
    INSTANCE_NAME=postgres-instance-1
    DATABASE_NAME=postgres
    SCHEMA_NAME=event
    HOST={{ .Release.Name }}-postgresql-svc.{{ .Release.Namespace }}
    PORT=5432
    USERNAME=event
    PASSWORD={{ randAlphaNum 32 }}
{{- end }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-pare-eventing-from-claim
type: Opaque
---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-pentium-postgres" .Release.Name)) -}}
apiVersion: v1
{{- if $secret }}
data:
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace  (printf "%s-pentium-postgres" .Release.Name)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- if  $secretData }}
    {{- range $oldkey, $oldvalue := $secretData }}
    {{ $oldkey }}: {{ $oldvalue | quote }}
    {{- end }}
  {{- end }}
{{- else }}
stringData:
  pentium-postgres: |
    INSTANCE_NAME=postgres-instance-1
    DATABASE_NAME=postgres
    SCHEMA_NAME=po
    HOST={{ .Release.Name }}-postgresql-svc.{{ .Release.Namespace }}
    PORT=5432
    USERNAME=po
    PASSWORD={{ randAlphaNum 32 }}
{{- end }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-pentium-postgres
type: Opaque