x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '1.0.0'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  deployerServiceAccount:
    description: >
      Creates app resources, including the CRD & RBAC.
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups:
            - 'apiextensions.k8s.io'
            resources:
            - 'customresourcedefinitions'
            verbs:
            - '*'
          - apiGroups:
            - 'rbac.authorization.k8s.io'
            resources:
            - 'clusterroles'
            - 'clusterrolebindings'
            verbs:
            - '*'
  # The images property will be filled in during part 2
  images:
    '':
      properties:
        deployer.image.repo:
          type: REPO_WITH_REGISTRY
        deployer.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  adminUserAccount:
    type: string
    title: Rapd admin e-mail address
    default: noreply@example.com
    # https://www.w3.org/TR/html52/sec-forms.html#email-state-typeemail
    pattern: ^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$
  domain:
    title: Rapd domain host
    description: Please configure your domain as a CNAME record pointing to our service domain in your DNS settings. 
    type: string
#  certificate:
#    title: GCP certificate name
#    description: Please enter the name of the pre-created Google management certificate.
#    type: string
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: tls.base64EncodedPrivateKey
          base64EncodedCertificate: tls.base64EncodedCertificate    

required:
- name
- namespace
- adminUserAccount
