apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-event-handler
  name: {{ .Release.Name }}-event-handler
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-event-handler
  ports:
    - protocol: TCP
      port: {{ .Values.eventHandler.service.port }}
      targetPort: {{ .Values.eventHandler.service.port }}
  type: ClusterIP
