apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-authenticator
  name: {{ .Release.Name }}-authenticator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-authenticator
  ports:
    - protocol: TCP
      port: {{ .Values.authenticator.service.port }}
      targetPort: {{ .Values.authenticator.service.port }}
  type: ClusterIP
