{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-pare-eventing-app-config-file" .Release.Name)) -}}
{{- $key := randAlphaNum 32 -}}
{{ $b64key := b64enc $key }}
{{ $b64urlkey := replace "+" "-" (replace "/" "_" $b64key) }}
{{- $existingMasterKeys := "" -}}
{{- $existingSecretKeys := "" -}}
{{- if $secret -}}
  {{- $envLines := splitList "\n" (index $secret.data ".env" | b64dec) -}}
  {{- range $envLines -}}
    {{- $line := . -}}
    {{- $key := regexFind "^([^=]+)=" $line -}}
    {{- $value := regexReplaceAll "^([^=]+)=" $line "" -}}
    {{- if eq (trim $key) "MASTER_KEYS=" -}}
      {{- $existingMasterKeys = trim $value -}}
    {{- end -}}
    {{- if eq (trim $key) "SECRET_KEYS=" -}}
      {{- $existingSecretKeys = trim $value -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
stringData:
  .env: |
    LOGLEVEL=INFO
    DEPLOY_MODE=production
    # Base URL for accessing backend services.
    EVENTING_SERVICE_HOST=0.0.0.0
    EVENTING_SERVICE_PORT=8004
    SERVICE_URL=http://${EVENTING_SERVICE_HOST}:${EVENTING_SERVICE_PORT}
    RETRY_DELAY_SECONDS=3
    DELIVER_TIMEOUT = 150
    MIGRATE_DB=true
    MAX_CONCURRENT_SLOTS=1
    MAX_DELAY_SECONDS=60
    MASTER_KEYS={{ ternary $b64urlkey $existingMasterKeys (empty $existingMasterKeys) }}
    SECRET_KEYS={{ ternary (printf "%x" $key) $existingSecretKeys (empty $existingSecretKeys) }}
metadata:
  name: {{ .Release.Name }}-pare-eventing-app-config-file
type: Opaque