apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pare-eventing-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.pareEventingApi.service.port  }}
      targetPort: {{ .Values.pareEventingApi.service.port  }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-pare-eventing-api