apiVersion: v1
kind: Service
metadata:
  name: engine-k3s-v1
spec:
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: 6443
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: {{ .Release.Name }}-controller-manager
  type: ClusterIP
