---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-minio" .Release.Name)) -}}
# Source: pare-minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: minio
    release: {{ .Release.Name }}
    heritage: Helm
type: Opaque
data:
  rootUser: "bWluaW8="
  {{- if $secret }}
  rootPassword: {{ $secret.data.rootPassword }}
  {{- else }}
  rootPassword: {{ randAlphaNum 32 | b64enc }}
  {{- end }}