apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-f2e
  name: {{ .Release.Name }}-f2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-f2e
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-f2e
    spec:
      containers:
      - image: {{ .Values.f2e.deployment.image.name }}:{{ .Values.f2e.deployment.image.tag }}
        name: f2e
        resources: {}
        volumeMounts:
        - name: f2e-config
          mountPath: /usr/share/nginx/html/rapd.config
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{ .Release.Name }}-nginx-config
          items:
          - key: default.conf
            path: default.conf
      - name: f2e-config
        configMap:                                                                                                        
          defaultMode: 420                                                                                                
          name: {{ .Release.Name }}-f2e-config-json                                                                                      
          optional: false                                                                                                 
