apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-f2e
  name: {{ .Release.Name }}-f2e
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-f2e
  ports:
    - protocol: TCP
      name: f2e
      port: {{ .Values.f2e.service.port }}
      targetPort: {{ .Values.f2e.service.port }}
    - protocol: TCP
      name: nginx
      port: 80
      targetPort: 80 
  type: NodePort
