apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-payment-check
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - curl -X POST http://{{ .Release.Name }}-event-handler.{{ .Release.Namespace }}:{{ .Values.eventHandler.service.port }}/events/trigger_payment_check
            image: public.ecr.aws/d3c8d7n6/alpine/curl
            imagePullPolicy: IfNotPresent
            name: curl
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '0 0 * * *'
  successfulJobsHistoryLimit: 3
  suspend: false