apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Release.Name }}-event-gateway-healthcheck
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8000
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: {{ .Release.Name }}-event-gateway