{{- $redisPassword :=  randAlphaNum 32  -}}
---

{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-redis-secret" .Release.Name)) -}}
# Source: pare-redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  {{- if $secret }}
  redis-password: {{ index $secret.data "redis-password" | b64enc }}
  {{- else }}
  redis-password: {{ $redisPassword | b64enc }}
  {{- end }}

---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-redis-config-file" .Release.Name)) -}}
apiVersion: v1
{{- if $secret }}
data:
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace  (printf "%s-redis-config-file" .Release.Name)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- if  $secretData }}
    {{- range $oldkey, $oldvalue := $secretData }}
    {{ $oldkey }}: {{ $oldvalue | quote }}
    {{- end }}
  {{- end }}
{{- else }}
stringData:
  redis:  |
    HOST="{{ .Release.Name }}-redis.{{ .Release.Namespace }}"
    PORT=6379
    USERNAME=""
    PASSWORD={{ $redisPassword | quote }}
    DATABASE_NUMBER=0
    REDIS_URL="redis://:{{ $redisPassword }}@{{ .Release.Name }}-redis.{{ .Release.Namespace }}:6379/0"
{{- end }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-config-file
type: Opaque