apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "partner", "product_id": "rapd", "partner_name": "Partner"}'
spec:
  descriptor:
    type: RAPD
    version: '1.0.0'
    description: >-
      RAPD is ...
  info:
  {{- if .Values.certificate  }}
  - name: Rapd site domain
    type: Reference
    valueFrom:
      ingressRef:
        name: {{ .Release.Name }}-nginx
  {{- else }}
  - name: Rapd site address
    type: Reference
    valueFrom:
      ingressRef:
        name: {{ .Release.Name }}-nginx
        protocol: HTTPS
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  addOwnerRef: true
  componentKinds:
  - group: ''
    kind: PersistentVolumeClaim
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: apps
    kind: Deployment
  - group: networking.k8s.io/v1
    kind: Ingress
  - group: ''
    kind: ServiceAccount
  - group: ''
    kind: ConfigMap
  - group: batch
    kind: Job
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: apps
    kind: StatefulSet
  - group: batch/v1
    kind: CronJob
  - group: rbac.authorization.k8s.io/v1
    kind: Role
  - group: rbac.authorization.k8s.io/v1
    kind: RoleBinding
