# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: {{ .Release.Name }}-apiserver
#   namespace: {{ .Release.Namespace }}
# spec:
#   parentRefs:
#   - group: gateway.networking.k8s.io
#     kind: Gateway
#     name: rapd
#     namespace: {{ .Release.Namespace }}
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: {{ .Values.apiserver.httproute.prefixPath.path }}
#     backendRefs:
#     - name: {{ .Release.Name }}-apiserver
#       port: {{ .Values.apiserver.service.port }}
#       kind: Service
#       weight: 1
#       group: ""


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-apiserver
#   namespace: {{ .Release.Namespace }}
#   annotations:
#   {{- if .Values.certificate  }}
#     networking.gke.io/managed-certificates: {{ .Values.certificate }}
#   {{- end }}
#     kubernetes.io/ingress.class: "gce"
# spec:
#   rules:
#   - http:
#       paths:
#       - backend:
#           service:
#             name: {{ .Release.Name }}-apiserver
#             port:
#               number: {{ .Values.apiserver.service.port }}
#         path: {{ .Values.apiserver.httproute.prefixPath.path }}
#         pathType: Prefix
