# Source: pare-rabbitmq/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: pare-rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
    - name: epmd
      port: 4369
      targetPort: epmd
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: dist
      port: 25672
      targetPort: dist
    - name: http-stats
      port: 15672
      targetPort: stats
  selector: 
    app.kubernetes.io/name: pare-rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
  publishNotReadyAddresses: true
---
# Source: pare-rabbitmq/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: pare-rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      nodePort: null
    - name: epmd
      port: 4369
      targetPort: epmd
      nodePort: null
    - name: dist
      port: 25672
      targetPort: dist
      nodePort: null
    - name: http-stats
      port: 15672
      targetPort: stats
      nodePort: null
  selector: 
    app.kubernetes.io/name: pare-rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
---