name: build-and-push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'pentiumnetwork-rapd-public'
        options:
          - pentiumnetwork-rapd-public
      image_tag:
        description: 'Image tag'
        required: true
        type: string


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: auth gcp
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: pentiumnetwork-rapd-public

    - name: Submit Cloud Build
      run: |
        gcloud builds submit --config cloudbuild/deployer.yaml . --substitutions=_TAG=${{ inputs.image_tag }} --suppress-logs

